name: Man10Bank
version: 1.0
auther: [forest611]
softdepend:
  - Vault
  - Man10CommonLibs
  - Man10Mail
  - Essentials
  - Man10Score
main: red.man10.man10bank.Man10Bank
api-version: 1.20
commands:
  mbal:
    default: op
    description: /bal
  bal:
    default: op
    description: /bal
  balance:
    default: op
    description: /bal
  money:
    default: op
    description: /bal
  bank:
    default: op
    description: /bal
  atm:
    default: op
    description: /bal
  mpay:
    default: op
    description: bank pay
  mbaltop:
    default: op
    description: serverBalanceTop
  mloantop:
    default: op
    description: serverLoanTop
  mlend:
    default: op
    description: player loan
  pay:
    default: op
    description: vault pay
  deposit:
    default: op
    description: vault to bank
  withdraw:
    default: op
    description: bank to vault
  mchequeop:
    default: op
    description: issue money
  mcheque:
    default: op
    description: issue chheque
  mrevo:
    default: op
    description: server loan system
  ballog:
    default: op
    description: bank log
